apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudops-app.fullname" . }}-backend
  labels:
    app: {{ include "cloudops-app.name" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloudops-app.name" . }}-backend
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "cloudops-backend"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/cloudops/backend"
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "secret/data/cloudops/backend" -}}`}}
          export MONGO_URI="{{`{{ .Data.data.MONGO_URI }}`}}"
          {{`{{- end }}`}}
      labels:
        app: {{ include "cloudops-app.name" . }}-backend
    spec:
      serviceAccountName: cloudops-app-backend
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          command:
            - sh
            - -c
          args:
            - ". /vault/secrets/config && exec node server.js"