apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudops-app.fullname" . }}-backend
  labels:
    app: {{ include "cloudops-app.name" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ include "cloudops-app.name" . }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
