apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudops-app.fullname" . }}-frontend
  labels:
    app: {{ include "cloudops-app.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloudops-app.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "cloudops-app.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
