apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudops-app.fullname" . }}-frontend
  labels:
    app: {{ include "cloudops-app.name" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "cloudops-app.name" . }}-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
