apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudops-app.fullname" . }}-mongodb
  labels:
    app: {{ include "cloudops-app.name" . }}-mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    app: {{ include "cloudops-app.name" . }}-mongodb
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
      protocol: TCP
